---
- name: Prepare Node.js environment on private EC2s
  hosts: private_ec2s
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all system packages to latest
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - curl
          - build-essential
        state: present

    - name: Install Node.js 18.x (LTS) if not installed
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Ensure npm is installed
      shell: |
        apt-get install -y npm
      args:
        creates: /usr/bin/npm

    - name: Ensure pm2 is installed globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Ensure pm2 startup is configured for ubuntu user
      shell: |
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
      args:
        creates: /etc/systemd/system/pm2-ubuntu.service
      become_user: ubuntu
