---
- name: Deploy Node.js app via Bastion
  hosts: private_ec2s
  become: true
  vars:
    repo_url: "https://github.com/ShamailAbbas/nodejs-with-all-aws-services-terraform.git"
    app_root: "/home/ubuntu/nodejs-with-all-aws-services-terraform"
    backend_dir: "/home/ubuntu/nodejs-with-all-aws-services-terraform/video-cms-backend"

    # Environment variables
    env_vars:
      DB_SECRET_NAME: "video-cms-db-very-very-secret-7gd9"
      AWS_REGION: "us-east-1"
      S3_BUCKET_NAME: "video-cms-media-dev-2312312312sashdhjahsdkjhask"
      CLOUDFRONT_URL: "https://dnzxlykel928t.cloudfront.net"
      REDIS_HOST: "video-cms-redis.t1bzyy.0001.use1.cache.amazonaws.com"
      REDIS_PORT: 6379
      PORT: 5000

  tasks:

    - name: Update system packages
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure dependencies are installed
      apt:
        name:
          - git
          - curl
          - build-essential
        state: present

    - name: Install Node.js (LTS 18.x)
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Ensure pm2 is installed globally
      npm:
        name: pm2
        global: yes
        state: present

    - name: Clone or update the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_root }}"
        version: main
        force: yes
      register: git_clone

    - name: Install backend dependencies
      npm:
        path: "{{ backend_dir }}"
        production: yes

    - name: Create .env file for environment variables
      copy:
        dest: "{{ backend_dir }}/.env"
        content: |
          {% for key, value in env_vars.items() %}
          {{ key }}={{ value }}
          {% endfor %}
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Stop existing pm2 process if running
      shell: |
        pm2 stop nodeapp || true
      args:
        chdir: "{{ backend_dir }}"
      ignore_errors: true

    - name: Start Node.js app with pm2
      shell: |
        pm2 start app.js --name nodeapp --env production
        pm2 save
      args:
        chdir: "{{ backend_dir }}"

    - name: Enable pm2 startup on boot
      shell: |
        pm2 startup systemd -u ubuntu --hp /home/ubuntu
        pm2 save
